### ISSUE TITLE
QT API timeout/disconnect issue

### ISSUE THREAD

**Issue by rickb99881** [tgardiner/questrade_api#14]
Hello team,  

I have been running the API for a couple weeks now and it works fine; however, it seems to time out after a couple days or only after 1 or 2 days.

There is no exact interval of disconnect/timeout period. Please see the error below. I have to go into APP HUB and refresh the token and input into code then it starts working again. Is there a way to avoid this timeout issue? 

Thank you. 

Traceback (most recent call last):
  File "/home/compadmin/Documents/PYTHON/QT_APP_01/API.py", line 6, in <module>
    print(q.time)
  File "/home/compadmin/.local/lib/python3.10/site-packages/questrade_api/questrade.py", line 81, in time
    return self.__get(self.config['API']['time'])
  File "/home/compadmin/.local/lib/python3.10/site-packages/questrade_api/questrade.py", line 49, in __get
    r = urllib.request.urlopen(req)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
 
 File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
compadmin@VM01:~/Documents/PYTHON/QT_APP_01$ /bin/python3 /home/compadmin/Documents/PYTHON/QT_APP_01/API.py
Traceback (most recent call last):
  File "/home/compadmin/Documents/PYTHON/QT_APP_01/API.py", line 6, in <module>
    print(q.time)
  File "/home/compadmin/.local/lib/python3.10/site-packages/questrade_api/questrade.py", line 81, in time
    return self.__get(self.config['API']['time'])
  File "/home/compadmin/.local/lib/python3.10/site-packages/questrade_api/questrade.py", line 49, in __get
    r = urllib.request.urlopen(req)
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by tgardiner** [comment]
This is likely caused by Questrade's REST API being unavailable for a short time.
